# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python35\Lib\site-packages\PyQt5\CalculadoraPia.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalculadoraDialog(object):
    def setupUi(self, CalculadoraDialog):
        CalculadoraDialog.setObjectName("CalculadoraDialog")
        CalculadoraDialog.resize(401, 436)
        self.lbl_primer_num = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_primer_num.setGeometry(QtCore.QRect(30, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_primer_num.setFont(font)
        self.lbl_primer_num.setObjectName("lbl_primer_num")
        self.lbl_segundo_num = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_segundo_num.setGeometry(QtCore.QRect(30, 110, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_segundo_num.setFont(font)
        self.lbl_segundo_num.setObjectName("lbl_segundo_num")
        self.txt_primer_num = QtWidgets.QLineEdit(CalculadoraDialog)
        self.txt_primer_num.setGeometry(QtCore.QRect(280, 40, 113, 20))
        self.txt_primer_num.setObjectName("txt_primer_num")
        self.txt_segundo_num = QtWidgets.QLineEdit(CalculadoraDialog)
        self.txt_segundo_num.setGeometry(QtCore.QRect(280, 110, 113, 20))
        self.txt_segundo_num.setObjectName("txt_segundo_num")
        self.btn_dividir = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_dividir.setGeometry(QtCore.QRect(270, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_dividir.setFont(font)
        self.btn_dividir.setObjectName("btn_dividir")
        self.btn_restar = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_restar.setGeometry(QtCore.QRect(120, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_restar.setFont(font)
        self.btn_restar.setObjectName("btn_restar")
        self.btn_sumar = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_sumar.setGeometry(QtCore.QRect(120, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_sumar.setFont(font)
        self.btn_sumar.setObjectName("btn_sumar")
        self.btn_multiplicar = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_multiplicar.setGeometry(QtCore.QRect(270, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_multiplicar.setFont(font)
        self.btn_multiplicar.setObjectName("btn_multiplicar")
        self.lbl_resultado = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_resultado.setGeometry(QtCore.QRect(50, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_resultado.setFont(font)
        self.lbl_resultado.setObjectName("lbl_resultado")

        self.retranslateUi(CalculadoraDialog)
        QtCore.QMetaObject.connectSlotsByName(CalculadoraDialog)

    def retranslateUi(self, CalculadoraDialog):
        _translate = QtCore.QCoreApplication.translate
        CalculadoraDialog.setWindowTitle(_translate("CalculadoraDialog", "Calculadora"))
        self.lbl_primer_num.setText(_translate("CalculadoraDialog", "Ingrese el primero numero"))
        self.lbl_segundo_num.setText(_translate("CalculadoraDialog", "Ingrese el segundo numero"))
        self.btn_dividir.setText(_translate("CalculadoraDialog", "/"))
        self.btn_restar.setText(_translate("CalculadoraDialog", "-"))
        self.btn_sumar.setText(_translate("CalculadoraDialog", "+"))
        self.btn_multiplicar.setText(_translate("CalculadoraDialog", "x"))
        self.lbl_resultado.setText(_translate("CalculadoraDialog", "Resultado"))
